export const weeks = [
  {
    week: 1,
    type: "learning",
    subject: "NEXT For Autism Learning Week: Professional Connection",
    description: "This week's topic in NEXT Connects is professional connection. You will learn what professional connection means and how it can help you grow at work and in life.",
    footer: "Next week: you will meet your matched professional and start learning together.",
    items: [
      { text: "Video: What is NEXT For Autism?", link: "https://vimeo.com/1135356068?share=copy&fl=sv&fe=ci" },
      { text: "Assignment: Professional Communication Guide", link: "https://drive.google.com/file/d/1FcELgUl-_mTD1Bn4LI_bcEIpUQZDEC0-/view?usp=share_link" },
      { text: "Assignment: Pre-Session Worksheet", link: "https://drive.google.com/file/d/1q6_tfUcUk7F3zrtdQgl5SI9Y5UqZpF_g/view?usp=share_link" },
      { text: "Assignment: Schedule a meeting with your matched professional", link: "https://docs.google.com/document/d/1SeVK2SldbBOvKiPOj_XytbAVyohuZKzOylELLOjbCy8/edit?usp=sharing" },
    ],
  },
  {
    week: 2,
    type: "discussion",
    subject: "NEXT For Autism Discussion Week: Time for Your First Chat",
    description: "It is discussion week in NEXT Connects. This is your chance to get to know each other and talk about what you have been learning so far.",
    footer: "We cannot wait to hear how your first meeting goes.",
    items: [
      { text: "Agenda: Professional Connection Agenda", link: "https://drive.google.com/file/d/1NsVmRllVbRohRPS9z0ETwb1Y8CK-KGwi/view?usp=share_link" },
      { text: "Discussion: Meet with your matched professional", link: "" },
      { text: "Assignment: Post-Session Worksheet", link: "https://drive.google.com/file/d/1q6_tfUcUk7F3zrtdQgl5SI9Y5UqZpF_g/view?usp=share_link" },
    ],
  },
  {
    week: 3,
    type: "learning",
    subject: "NEXT For Autism Learning Week: Goal Setting",
    description: "This week's topic for NEXT Connects is goal setting.",
    footer: "Next week: you will share your goals with your matched professional.",
    items: [
      { text: "Video: Goal Setting", link: "https://vimeo.com/1134698212?share=copy&fl=sv&fe=ci" },
      { text: "Assignment: SMART Goals Worksheet", link: "https://drive.google.com/file/d/1FcELgUl-_mTD1Bn4LI_bcEIpUQZDEC0-/view?usp=share_link" },
      { text: "Assignment: Pre-Session Worksheet", link: "https://drive.google.com/file/d/1dsPfM6yaejJ533m6kRZPaOZcSlCRxCqO/view?usp=share_link" },
      { text: "Assignment: Schedule a meeting with your matched professional", link: "https://docs.google.com/document/d/1SeVK2SldbBOvKiPOj_XytbAVyohuZKzOylELLOjbCy8/edit?usp=sharing" },
    ],
  },
  {
    week: 4,
    type: "discussion",
    subject: "NEXT For Autism Discussion Week: Let's Talk About Your Goals",
    description: "This week, meet with your matched professional to talk about your goals.",
    footer: "Choose 1-2 goals to focus on together.",
    items: [
      { text: "Review: SMART Goals Worksheet", link: "https://drive.google.com/file/d/1FcELgUl-_mTD1Bn4LI_bcEIpUQZDEC0-/view?usp=share_link" },
      { text: "Agenda: Goal Setting Agenda", link: "https://drive.google.com/file/d/1dWate9NOpJhNtGxMVQxUT4iECp15z-dW/view?usp=share_link" },
      { text: "Discussion: Meet with your matched professional", link: "" },
      { text: "Assignment: Post-Session Worksheet", link: "https://drive.google.com/file/d/1dsPfM6yaejJ533m6kRZPaOZcSlCRxCqO/view?usp=share_link" },
    ],
  },
  {
    week: 5,
    type: "learning",
    subject: "NEXT For Autism Learning Week: Learning About Communication",
    description: "This week's lesson is about communication styles and strategies.",
    footer: "Great communication makes every partnership stronger.",
    items: [
      { text: "Video: Communication", link: "https://vimeo.com/1134698406?share=copy&fl=sv&fe=ci" },
      { text: "Review: Professional Connection Form", link: "https://drive.google.com/file/d/1c2MJiC6CA9c8MzLVGlX5x-NElmzK2BJi/view?usp=share_link" },
      { text: "Assignment: Pre-Session Worksheet", link: "https://drive.google.com/file/d/1i9QrC9RewFnR25vLFShw_wI2dqR_A97Z/view?usp=share_link" },
      { text: "Assignment: Schedule a meeting with your matched professional", link: "https://docs.google.com/document/d/1SeVK2SldbBOvKiPOj_XytbAVyohuZKzOylELLOjbCy8/edit?usp=sharing" },
    ],
  },
  {
    week: 6,
    type: "discussion",
    subject: "NEXT For Autism Discussion Week: Let's Talk About Communication",
    description: "It is time for another meeting with your matched professional.",
    footer: "",
    items: [
      { text: "Agenda: Communication Agenda", link: "https://drive.google.com/file/d/1TB4vIVTGsJo_oDSS2oiMaw5jId7unz2_/view?usp=share_link" },
      { text: "Discussion: Meet with your matched professional", link: "" },
      { text: "Assignment: Post-Session Worksheet", link: "https://drive.google.com/file/d/1i9QrC9RewFnR25vLFShw_wI2dqR_A97Z/view?usp=share_link" },
    ],
  },
  {
    week: 7,
    type: "learning",
    subject: "NEXT For Autism Learning Week: Workplace Intangibles",
    description: "Learn about soft skills like teamwork and attitude.",
    footer: "",
    items: [
      { text: "Assignment: Workplace Intangibles", link: "https://drive.google.com/file/d/1dFEz-LUU8tkGITb9Zcfxr29bqZftVTeH/view?usp=share_link" },
      { text: "Video: Workplace Intangibles", link: "https://vimeo.com/1135353223?share=copy&fl=sv&fe=ci" },
      { text: "Assignment: Workplace Intangibles Worksheet", link: "https://drive.google.com/file/d/13jJwGMCTYKkvGPdGuzu-hD8CPiDl-p4h/view?usp=share_link" },
      { text: "Assignment: Pre-Session Worksheet", link: "https://drive.google.com/file/d/1dSe07WSSNupvtAxUZHPR-bBpRa9I9aSg/view?usp=share_link" },
      { text: "Assignment: Schedule a meeting with your matched professional", link: "https://docs.google.com/document/d/1SeVK2SldbBOvKiPOj_XytbAVyohuZKzOylELLOjbCy8/edit?usp=sharing" },
    ],
  },
  {
    week: 8,
    type: "discussion",
    subject: "NEXT For Autism Discussion Week: Let's Talk About Workplace Intangibles",
    description: "Share what you learned about soft skills.",
    footer: "",
    items: [
      { text: "Agenda: Intangibles Agenda", link: "https://drive.google.com/file/d/1q7gnFIrMP-hzq45urcsNdlfKUo1hIh0p/view?usp=share_link" },
      { text: "Discussion: Meet with your matched professional", link: "" },
      { text: "Assignment: Post-Session Worksheet", link: "https://drive.google.com/file/d/1dSe07WSSNupvtAxUZHPR-bBpRa9I9aSg/view?usp=share_link" },
    ],
  },
  {
    week: 9,
    type: "learning",
    subject: "NEXT For Autism Learning Week: Universal Design",
    description: "Learn how Universal Design helps make spaces and systems work better for everyone.",
    footer: "You are halfway through this guided professional connection. Great job.",
    items: [
      { text: "Video: Universal Design", link: "https://vimeo.com/1134721852?share=copy&fl=sv&fe=ci" },
      { text: "Review: Universal Design Guide", link: "https://drive.google.com/file/d/1fhxt9ZT54bE9DFvR805dIm_W7caAW_IQ/view?usp=share_link" },
      { text: "Review: Accommodation Request Letter", link: "https://drive.google.com/file/d/1pVLIHoLvYVw_1MPPhTHdF_-t_Gc-e7SQ/view?usp=share_link" },
      { text: "Assignment: Pre-Session Worksheet", link: "https://drive.google.com/file/d/19zpRZbaIIYpVdM_x2EVX2Z0nhlvcavqC/view?usp=share_link" },
      { text: "Assignment: Schedule a meeting", link: "https://docs.google.com/document/d/1SeVK2SldbBOvKiPOj_XytbAVyohuZKzOylELLOjbCy8/edit?usp=sharing" },
    ],
  },
  {
    week: 10,
    type: "discussion",
    subject: "NEXT For Autism Discussion Week: Let's Talk About Universal Design",
    description: "Talk about how small changes can make workplaces easier for everyone.",
    footer: "",
    items: [
      { text: "Agenda: Universal Design Agenda", link: "https://drive.google.com/file/d/1U39d0DNwkWkWFRP3_XmhUP0d82wyfGTT/view?usp=share_link" },
      { text: "Discussion: Meet with your matched professional", link: "" },
      { text: "Assignment: Post-Session Worksheet", link: "https://drive.google.com/file/d/19zpRZbaIIYpVdM_x2EVX2Z0nhlvcavqC/view?usp=share_link" },
    ],
  },
  {
    week: 11,
    type: "learning",
    subject: "NEXT For Autism Learning Week: The Job Search",
    description: "Learn about finding the right job fit.",
    footer: "These tools will help you feel more confident.",
    items: [
      { text: "Video: Job Search", link: "https://vimeo.com/1134696816?share=copy&fl=sv&fe=ci" },
      { text: "Review: Inclusive Job Description", link: "https://drive.google.com/file/d/1MJvmB8DlyIeD31T7Mh-MYSMSB6WBEq00/view?usp=share_link" },
      { text: "Assignment: Pre-Session Worksheet", link: "https://drive.google.com/file/d/1lew8hvhaHUAl5OsZ_7hSf4jxxoms7IuG/view?usp=share_link" },
      { text: "Assignment: Schedule a meeting", link: "https://docs.google.com/document/d/1SeVK2SldbBOvKiPOj_XytbAVyohuZKzOylELLOjbCy8/edit?usp=sharing" },
    ],
  },
  {
    week: 12,
    type: "discussion",
    subject: "NEXT For Autism Discussion Week: Talking About Job Search",
    description: "Meet with your matched professional again.",
    footer: "",
    items: [
      { text: "Agenda: Job Search Agenda", link: "https://drive.google.com/file/d/1w2crTwGb7TD6tDwm0DWqQ6dmcI6BHt5d/view?usp=share_link" },
      { text: "Discussion: Meet with your matched professional", link: "" },
      { text: "Assignment: Post-Session Worksheet", link: "https://drive.google.com/file/d/1lew8hvhaHUAl5OsZ_7hSf4jxxoms7IuG/view?usp=share_link" },
    ],
  },
  {
    week: 13,
    type: "learning",
    subject: "NEXT For Autism Learning Week: Getting Ready for Interviews",
    description: "Interviews can be tricky. This lesson makes it easier.",
    footer: "",
    items: [
      { text: "Video: Interviewing", link: "https://vimeo.com/1134697545?share=copy&fl=sv&fe=ci" },
      { text: "Assignment: Prep Guide", link: "https://drive.google.com/file/d/1tQn5-nqbfHwhbmn9eRwg_bLl0-iSHE99/view?usp=share_link" },
      { text: "Assignment: Checklist", link: "https://drive.google.com/file/d/1fcLOO2cuiUv_DpcQfEsrHtZHQ7NXX_FN/view?usp=share_link" },
      { text: "Assignment: Pre-Session Worksheet", link: "https://drive.google.com/file/d/1WpoL2YS4JTWmbirJ538mZTrvUq7Ay_ZV/view?usp=share_link" },
      { text: "Assignment: Schedule a meeting", link: "https://docs.google.com/document/d/1SeVK2SldbBOvKiPOj_XytbAVyohuZKzOylELLOjbCy8/edit?usp=sharing" },
    ],
  },
  {
    week: 14,
    type: "discussion",
    subject: "NEXT For Autism Discussion Week: Talking About Interviewing",
    description: "Practice and discuss interviews.",
    footer: "",
    items: [
      { text: "Agenda: Interviewing Agenda", link: "https://drive.google.com/file/d/1ci7xnLv9nwvvRcgZe1rEw4hABsPlVlGr/view?usp=share_link" },
      { text: "Discussion: Practice interview", link: "" },
      { text: "Assignment: Post-Session Worksheet", link: "https://drive.google.com/file/d/1WpoL2YS4JTWmbirJ538mZTrvUq7Ay_ZV/view?usp=share_link" },
    ],
  },
  {
    week: 15,
    type: "learning",
    subject: "NEXT For Autism Learning Week: Mindful Feedback",
    description: "Learn how to give and receive feedback effectively.",
    footer: "You are almost done.",
    items: [
      { text: "Video: Mindful Feedback", link: "https://vimeo.com/1135354938?share=copy&fl=sv&fe=ci" },
      { text: "Assignment: Pre-Session Worksheet", link: "https://drive.google.com/file/d/1t9sOL43-NHrC7KDiisl4FnOzWAz5nfTe/view?usp=share_link" },
      { text: "Assignment: Schedule a meeting", link: "https://docs.google.com/document/d/1SeVK2SldbBOvKiPOj_XytbAVyohuZKzOylELLOjbCy8/edit?usp=sharing" },
    ],
  },
  {
    week: 16,
    type: "discussion",
    subject: "NEXT For Autism: Final Discussion and Celebration",
    description: "Final meeting and reflection.",
    footer: "Congratulations. You made it to the final week.",
    items: [
      { text: "Agenda: Mindful Feedback Agenda", link: "https://drive.google.com/file/d/1fmy1iLBw__iPwybBces5isywj-oGkLPj/view?usp=share_link" },
      { text: "Assignment: Post-Session Worksheet", link: "https://drive.google.com/file/d/1t9sOL43-NHrC7KDiisl4FnOzWAz5nfTe/view?usp=share_link" },
      { text: "Discussion: Meet with your matched professional and reflect", link: "" },
      { text: "Assignment: Post-Program Survey", link: "https://docs.google.com/forms/d/e/1FAIpQLScf3Yfwk4XKMWPVf_UbFnj2_Zn32rxyeSDpxqOSQE-a65ctzA/viewform?usp=header" },
    ],
  },
];
